language: python
python: 3.5
sudo: false
cache: pip
env:
  - TOXENV=flake8-py27
  - TOXENV=flake8-py35
  - TOXENV=readme-py27
  - TOXENV=py27-dj18
  - TOXENV=py27-dj19
  - TOXENV=py27-dj110
  - TOXENV=py27-djmaster
  - TOXENV=py34-dj18
  - TOXENV=py34-dj19
  - TOXENV=py34-dj110
  - TOXENV=py34-djmaster
  - TOXENV=py35-dj18
  - TOXENV=py35-dj19
  - TOXENV=py35-dj110
  - TOXENV=py35-djmaster
  - TOXENV=pypy-dj18
  - TOXENV=pypy-dj19
  - TOXENV=pypy-dj110
  - TOXENV=pypy-djmaster
install:
  - pip install tox codecov
script: tox -v
after_success:
  - codecov
deploy:
  provider: pypi
  user: jazzband
  distributions: "sdist bdist_wheel"
  password:
    secure: B7imNYNndd2HEr79+3/jXLjFo/MdzzHUkH1NJ7G+YFtYjEkRFEaVuPXhuX1LYO9/qzYDcqHVrnsg65ZUXCftAg0/zFZ7zhEn/WEYZA2nkPosoSrYNV+s3XH/DMmpXdG6mKRN4D0mLQXaCwGeuQ2wHFOg7HCsz+tojFwYnEyN9ag=
  on:
    tags: true
    repo: jazzband/django-dbtemplates
    python: "2.7"
    condition: "$TOXENV = py27-dj110"
