language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
sudo: false
cache: pip
install:
  - pip install tox-travis
script: tox -v
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: pypi
  user: jazzband
  distributions: "sdist bdist_wheel"
  password:
    secure: B7imNYNndd2HEr79+3/jXLjFo/MdzzHUkH1NJ7G+YFtYjEkRFEaVuPXhuX1LYO9/qzYDcqHVrnsg65ZUXCftAg0/zFZ7zhEn/WEYZA2nkPosoSrYNV+s3XH/DMmpXdG6mKRN4D0mLQXaCwGeuQ2wHFOg7HCsz+tojFwYnEyN9ag=
  on:
    tags: true
    repo: jazzband/django-dbtemplates
    python: 3.6
